import Head from 'next/head'
import Header from "../../components/Header"
import { getSettings } from '../../controllers/general'
import { useDispatch, useSelector } from 'react-redux'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Footer from '../../components/Footer'
import Lottie from 'react-lottie';
import * as loadAnim from "../../assets/images/loading.json"
import bg from "../../assets/images/bg.jpg"
import { Col, Divider, Form, Input, Row } from 'antd'
import { useSession } from 'next-auth/react'

const loaderOptions = {
  loop: true,
  autoplay: true, 
  animationData: loadAnim,
  rendererSettings: {
    preserveAspectRatio: 'xMidYMid slice'
  }
};

export default function User({settingsData}) {
  let sets = useSelector((state) => state.settings)
  const dispatch = useDispatch()
  const router = useRouter()
  const {data: session, status} = useSession()
  useEffect(() => {
    if(status !== "authenticated"){
      router.push("/")
    }
    if(!sets.loaded){
      dispatch({
        type: "FETCH_API",
        payload: {
          ...settingsData,
          loaded: true
        }
      })
      router.push("/my-account")
    }
  },[sets, status])
  const [active, setActive] = useState("account")
  return (
    <div className="home">
      <Head>
        <title>SwitchOff - My Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id={'globalLoader'}>
        <Lottie options={loaderOptions}
        height={200}
        isClickToPauseDisabled={true}
        width={200}/>
      </div>
      <Header headerSettings={settingsData}/>
      <section className="account-header">
        <img src={bg.src} alt="" />
        <div className="overlay" />
      </section>
      <section className="account-container">
        <div className="container">
          <Row gutter={[10,10]}>
            <Col md={5}>
              <div className='account-menu'>
                <h2 className="account-menu-title">My Account</h2>
                <Divider style={{marginBlock: 4}} />
                <div className={`account-menu-item active`}><i className="fa-solid fa-user"></i> My Profile</div> 
                <div className={`account-menu-item`}><i className="fa-solid fa-calendar-days"></i> My Bookings</div> 
                <div className={`account-menu-item`}><i className="fa-solid fa-bookmark"></i> Favourites</div>
              </div>
            </Col>
            <Col md={19}>
              <div className="account-tabs">
                <h2 className="account-tabs-title">
                  Hi
                </h2>
                <Form>
                  <Row gutter={[10,10]}>
                    <Col md={12}>
                    <Form.Item>
                      <Input />
                    </Form.Item>
                    <Form.Item>
                      <Input />
                    </Form.Item>
                    </Col>
                  </Row>
                </Form>
              </div>
            </Col>
          </Row>
        </div>
      </section>
      <Footer footer={settingsData.footer} general={settingsData.general}/>
    </div>
  )
}

export async function getServerSideProps() {
  let res = await getSettings()
  return {
    props: {
      settingsData: res.settings,
      properties: res.properties,
      banners: res.banners
    }
  }
}
