import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header"
import { getProperties, getSettings } from '../controllers/general'
import { useDispatch, useSelector } from 'react-redux'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Banner from '../components/Banner'
import {AnimatePresence} from "framer-motion"
import Deals from '../components/Deals'
import Footer from '../components/Footer'
import { BannerSearch } from '../components/SearchBar'

export default function About({settingsData}) {
  let sets = useSelector((state) => state.settings)
  const dispatch = useDispatch()
  const router = useRouter()
  useEffect(() => {
    if(!sets.loaded){
      dispatch({
        type: "FETCH_API",
        payload: {
          ...settingsData,
          loaded: true
        }
      })
      router.push("/")
    }
  },[sets, dispatch, router, settingsData])
  return (
    <div className="home">
      <Head>
        <title>SwitchOff - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimatePresence>
        <Header theme={"dark"} headerSettings={settingsData}/>
        <div className="about-top">
            <h1>About SwitchOff</h1>
        </div>
        {/* <BannerSearch showAll={false} properties={result.properties} /> */}
        <div className="about">
            <div className="container">
                <p>Some switch-off in the mountains, some switch off at the beach, some switch-off to explore and travel that’ll teach. We at Switch-off aim to evolve the way everyone travels. From the grammable experience to the soul-nourishing feels – everything that travel has to offer is going to change with Switch-off.</p>
            </div>
        </div>
        {settingsData.homepage.deals.enabled && <Deals deals={settingsData.homepage.deals}/>}
        <Footer footer={settingsData.footer} general={settingsData.general}/>
      </AnimatePresence>
    </div>
  )
}

export async function getStaticProps() {
  let res = await getSettings()
  // let properties = await getProperties()
  return {
    props: {
      settingsData: res.settings
    }
  }
}
