import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header"
import { getSettings } from '../controllers/general'
import { useDispatch, useSelector } from 'react-redux'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Banner from '../components/Banner'
import SearchBar from '../components/SearchBar'
import {AnimatePresence} from "framer-motion"

export default function Home({settingsData}) {
  let sets = useSelector((state) => state.settings)
  // console.log(sets)
  const dispatch = useDispatch()
  const router = useRouter()
  useEffect(() => {
    if(!sets.loaded){
      dispatch({
        type: "FETCH_API",
        payload: {
          ...settingsData,
          loaded: true
        }
      })
      router.push("/")
    }
  },[sets])
  return (
    <div className="home">
      <Head>
        <title>SwitchOff - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimatePresence>
        <Header headerSettings={settingsData}/>
        <Banner banner={settingsData.homepage.banner} counts={settingsData.homepage.propCount}/>
        <SearchBar />
      </AnimatePresence>
    </div>
  )
}

export async function getStaticProps() {
  let res = await getSettings()
  return {
    props: {
      settingsData: res.data
    }
  }
}
