import Head from 'next/head'
import Header from "../../components/Header"
import { getSettings } from '../../controllers/general'
import { useDispatch, useSelector } from 'react-redux'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Footer from '../../components/Footer'
import Lottie from 'react-lottie';
import * as loadAnim from "../../assets/images/loading.json"
import { Button, Card, Col, Divider, Row, Space, Steps } from 'antd'

const loaderOptions = {
    loop: true,
    autoplay: true, 
    animationData: loadAnim,
    rendererSettings: {
      preserveAspectRatio: 'xMidYMid slice'
    }
  };

const Blogs = ({settingsData}) => {
    let sets = useSelector((state) => state.settings)
    const dispatch = useDispatch()

    //checkout steps
    const [step, setStep] = useState(0)

    const router = useRouter()
    useEffect(() => {
        if(!sets.loaded){
        dispatch({
            type: "FETCH_API",
            payload: {
            ...settingsData,
            loaded: true
            }
        })
        router.push("/blogs")
        }
    },[sets])
    return (
        <div className="home">
        <Head>
            <title>Checkout | SwitchOff</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div id={'globalLoader'}>
            <Lottie options={loaderOptions}
            height={200}
            isClickToPauseDisabled={true}
            width={200}/>
        </div>
        <Header headerSettings={settingsData}/>
        <section className="blogs">
          
        </section>
        <Footer footer={settingsData.footer} general={settingsData.general}/>
        </div>
    )
}

export async function getServerSideProps() {
    let res = await getSettings()
    return {
      props: {
        settingsData: res.settings
      }
    }
  }

export default Blogs